In [5]:
import pandas as pd
import Matchmaker_solver as solver

ModuleNotFoundError: No module named 'pandas'

Download the relavant spawn matrix as a CSV, upload to the jupyter notebook, and put the file name under 'file_location' between either ' ' or " ".

Ex: "2025_2026 KFH Spawn Matrix.xlsx - KFH_W2526_v3_spawn_matrix.csv"
 
Confirm that the shown rows match with the correct matrix.

In [ ]:
file_name = "C:/Users/jvkim/Downloads/2025_2026 KFH Spawn Matrix.xlsx - KFH_W2526_v3_spawn_matrix.csv"
matrix = pd.read_csv(file_name)

matrix = matrix.iloc[18:123, 0:86].rename(columns = matrix.iloc[17])
matrix["rank"] = matrix["rank"].astype(int)
matrix

,rank,F_P101,F_P102,F_P103,F_P104,F_P105,F_P106,F_P109,F_P110,F_P111,...,F_P178,F_P179,F_P181,F_P182,F_P183,F_P184,F_P186,F_P187,F_P188,F_P189
18,1,M_B273,M_B256,M_B216,M_B246,Mp_B299,M_B218,M_B224,M_B270,Mp_B181,...,Mp_B300,M_B238,M_B246,M_B191,M_B224,M_B225,M_B219,M_B194,M_B205,M_B254
19,2,M_B285,M_B225,M_B243,M_B190,M_B286,M_B199,M_B218,M_B219,Mp_B299,...,M_B196,M_B253,M_B268,M_B218,M_B242,M_B285,M_B255,M_B239,M_B192,M_B232
20,3,M_B268,Mp_B181,Mp_B186,Mp_B180,M_B244,M_B263,Mp_B181,M_B222,M_B216,...,M_B191,M_B245,M_B273,M_B217,M_B223,M_B295,M_B275,M_B206,M_B201,M_B205
21,4,M_B281,M_B243,Mp_B183,M_B243,M_B202,M_B209,Mp_B180,M_B233,M_B191,...,M_B272,M_B194,M_B281,M_B268,M_B245,M_B279,M_B252,Mp_B299,M_B191,M_B191
22,5,M_B271,M_B268,M_B285,M_B242,M_B203,M_B219,M_B270,Mp_B179,M_B279,...,M_B231,Mp_B300,M_B295,M_B194,M_B286,M_B243,M_B215,M_B223,M_B284,M_B228
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,101,**M_B222,**M_B196,**M_B203,**M_B274,**M_B294,**M_B288,**M_B235,**M_B263,**M_B293,...,**M_B290,**M_B265,**M_B202,**M_B282,**M_B285,M_B204,**M_B274,**M_B224,**M_B279,**M_B272
119,102,**M_B270,**M_B238,**M_B226,**M_B225,**M_B260,**M_B193,**M_B239,**Mp_B182,**M_B292,...,**M_B202,**M_B204,**Mp_B185,**M_B293,**M_B262,M_B289,**M_B203,**M_B232,**M_B267,**M_B257
120,103,**M_B294,**M_B264,**M_B266,**M_B248,**M_B205,**M_B234,**M_B236,**M_B232,**M_B270,...,**M_B265,**M_B273,**M_B290,**M_B240,**M_B237,Mp_B184,**M_B256,**M_B253,**M_B211,**M_B213
121,104,**M_B288,**M_B290,**M_B222,**M_B213,**M_B274,**M_B197,**M_B282,**M_B202,**M_B264,...,**M_B235,**M_B285,**M_B209,**M_B224,**M_B226,**M_B239,**M_B257,**M_B249,**M_B268,**M_B273
122,105,**M_B266,**M_B211,**M_B193,**M_B264,**M_B255,**M_B203,**M_B248,**M_B247,**M_B265,...,**M_B292,**M_B290,**M_B225,**M_B249,**M_B250,**M_B262,**M_B288,**M_B242,**M_B275,**M_B271

Input the current quarter, and females that are to be spawned

Ex:     
quarter = 4 

females = ["F_P101", "F_P102", "F_P103", "F_P104", "F_P105", "F_P106"]

*Ensure the females listed are typed correctly between ' ' or " " and that capitalization is correct

In [ ]:
quarter = 4
females = ["F_P101", "F_P102", "F_P103", "F_P104", "F_P105"]

male_file_name = "C:/Users/jvkim/Downloads/2025_2026 KFH Spawn Matrix.xlsx - Match Maker.csv"
male_use = pd.read_csv(male_file_name).iloc[398:500, 1:3].rename(columns = {"Males:": "Male", "Unnamed: 2" : "Uses"})
male_use["Uses"] = male_use["Uses"].astype(int)
male_use

        Male  Uses
398   M_B190     3
399   M_B191     4
400   M_B192     3
401   M_B193     2
402   M_B194     4
..       ...   ...
495  Mp_B181     0
496  Mp_B182     1
497  Mp_B183     1
498  Mp_B184     1
499  Mp_B185     3

[102 rows x 2 columns]

Run the solver. The number of avaliable solutions are shown, as well as the table for the top solution based on the spawn matrix ranking

In [ ]:
solutions = solver.matchmaker(matrix, females, male_use, quarter)
print(f"avaliable solutions: {len(solutions)}")
print("top solution:")
pd.DataFrame(solutions[0])

avaliable solutions: 112
top solution:

   F_P101   F_P102  F_P103  F_P104  F_P105
0  M_B271   M_B256  M_B214  M_B190  M_B202
1  M_B231  Mp_B181  M_B212  M_B242  M_B203
2  M_B237   M_B268  M_B293  M_B216  M_B288
3  M_B240   M_B293  M_B295  M_B197  M_B213
4  M_B236   M_B245  M_B224  M_B249  M_B240
5  M_B226   M_B271  M_B238  M_B223  M_B256

If that solution is not satisfactory, the other solutions may be viewed below by changing option variable, starting with 0 (the top solution) and going to the avaliable solution count. Note that the solutions are sorted by the sum of ranks, meaning that the top solution is the one where the males are highest on the spawn matrix. So as the option variable is increased, you will see progressively worse solutions.

In [ ]:
option = 1
print(f"sum of ranks: {solver.cost(solutions[option], matrix)}")
pd.DataFrame(solutions[option])

sum of ranks: 349

   F_P101   F_P102  F_P103  F_P104  F_P105
0  M_B271   M_B256  M_B214  M_B190  M_B202
1  M_B231  Mp_B181  M_B212  M_B242  M_B203
2  M_B237   M_B268  M_B293  M_B216  M_B288
3  M_B240   M_B293  M_B295  M_B197  M_B213
4  M_B236   M_B245  M_B224  M_B249  M_B240
5  M_B226   M_B271  M_B238  M_B223  M_B250

In [ ]:
solutions[option]

In [ ]:
invalid_males = [""]

for sol in solutions: